### ISSUE TITLE
Suggestion: Include Windows Environment Variable in Sessions folder example

### ISSUE THREAD

**Issue by MarcStocker** [kamiheku/noited#3]
This is a suggestion for the website itself. 

You have an example of where the Sessions Folder is located on Windows
`C:\Users\YOUR_NAME_HERE\AppData\LocalLow\Nolla_Games_Noita\save00\stats\sessions`

If instead of `YOUR_NAME_HERE` you used the Windows Environment Variable `%USERNAME%`, users could simply copy/paste without the need to replace the text `YOUR_NAME_HERE`. 

It's a very minor convenience improvement, but still an improvement in my opinion.

**Comment by kamiheku** [comment]
Excellent idea! Fixed in 491a32a.
